# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: python_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'python_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14python_service.proto\x12\nmcp_python\"\x1b\n\x0b\x43odeRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\"@\n\tCodeReply\x12\x0e\n\x06stdout\x18\x01 \x01(\t\x12\x0e\n\x06stderr\x18\x02 \x01(\t\x12\x13\n\x0breturn_code\x18\x03 \x01(\x05\x32Q\n\x0ePythonExecutor\x12?\n\x0b\x45xecuteCode\x12\x17.mcp_python.CodeRequest\x1a\x15.mcp_python.CodeReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'python_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CODEREQUEST']._serialized_start=36
  _globals['_CODEREQUEST']._serialized_end=63
  _globals['_CODEREPLY']._serialized_start=65
  _globals['_CODEREPLY']._serialized_end=129
  _globals['_PYTHONEXECUTOR']._serialized_start=131
  _globals['_PYTHONEXECUTOR']._serialized_end=212
# @@protoc_insertion_point(module_scope)
